/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/hackmerced2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

const Model2 = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/hackmerced2.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <pointLight name="Light" intensity={271757.065} decay={2} position={[8.281, 42.776, -3.518]} rotation={[-1.839, 0.602, 1.932]} />
        <PerspectiveCamera name="Camera" makeDefault={false} far={100} near={0.1} fov={22.895} position={[22.385, 49.897, 25.502]} rotation={[-0.53, 0.688, 0.356]} />
        <pointLight name="Light001" intensity={271757.065} decay={2} position={[-4.441, 40.329, 15.95]} rotation={[-1.839, 0.602, 1.932]} />
        <mesh name="Base" geometry={nodes.Base.geometry} material={materials['Material.001']} position={[0.041, 29.974, 0]} scale={[1, 2, 1]} />
        <mesh name="Head" geometry={nodes.Head.geometry} material={materials['Material.002']} position={[0.041, 36.7, 0]} />
        <mesh name="Roof" geometry={nodes.Roof.geometry} material={materials['Material.003']} position={[0.041, 40.105, 0]} rotation={[0, Math.PI / 4, 0]} />
        <group name="Cow" position={[-8, 35.972, 0]}>
          <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials['Matériau.002']} />
          <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials['Matériau.001']} />
          <mesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials.Matériau} />
          <mesh name="Cube_4" geometry={nodes.Cube_4.geometry} material={materials['Matériau.003']} />
          <mesh name="Cube_5" geometry={nodes.Cube_5.geometry} material={materials['Matériau.004']} />
          <pointLight name="Point" intensity={27175.707} decay={2} color="#00ffff" position={[-1.466, 1.698, 2.119]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <mesh name="Text" geometry={nodes.Text.geometry} material={materials.Material} position={[-2, 33, 2.62]} rotation={[Math.PI / 2, 0, 0]} scale={[1.49, 1, 1.429]}>
          <mesh name="Text001_1" geometry={nodes.Text001_1.geometry} material={materials.Material} position={[2.684, -5.24, 0]} rotation={[0, 0, Math.PI]} />
          <mesh name="Text002" geometry={nodes.Text002.geometry} material={materials.Material} position={[3.1, -0.52, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1.128, 0.671, 1]} />
          <mesh name="Text003" geometry={nodes.Text003.geometry} material={materials.Material} position={[-0.416, -4.72, 0]} rotation={[0, 0, Math.PI / 2]} scale={[1.128, 0.671, 1]} />
        </mesh>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[0.041, 23.049, 3.47]} scale={[2, 2.5, 1]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.003']} position={[0.041, 26.536, 3.47]} scale={[2.25, 1, 1.25]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[-7.455, 23.622, 0.01]} scale={[5, 3, 2.25]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.003']} position={[-7.455, 27.621, 0.01]} scale={[5, 1, 2.25]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[-0.017, 23.622, -7.489]} rotation={[0, Math.PI / 2, 0]} scale={[5, 3, 2.25]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.003']} position={[-0.017, 27.621, -7.489]} rotation={[0, Math.PI / 2, 0]} scale={[5, 1, 2.25]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.005']} position={[0.041, 26.536, 3.47]} scale={[2.25, 1, 1.25]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.006']} position={[0.041, 23.049, 3.47]} scale={[2, 2.5, 1]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.005']} position={[3.703, 25.555, -5]} rotation={[0, Math.PI / 2, 0]} scale={[2.3, 0.5, 1.5]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.006']} position={[3.708, 22.799, -5]} rotation={[0, Math.PI / 2, 0]} scale={[2, 2.25, 1.5]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.002']} position={[0.041, 19.515, 0]} />
      </group>
    </group>
  )
}

export default Model2;

useGLTF.preload('./models/hackmerced2.gltf')
