/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";

const Model3 = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/hackmerced3.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <pointLight
          name="Light"
          intensity={271757.065}
          decay={2}
          position={[8.281, 42.776, -3.518]}
          rotation={[-1.839, 0.602, 1.932]}
        />
        <PerspectiveCamera
          name="Camera"
          makeDefault={false}
          far={100}
          near={0.1}
          fov={22.895}
          position={[52.876, 58.118, 41.06]}
          rotation={[-0.615, 0.797, 0.468]}
        />
        <mesh
          name="Base"
          castShadow
          receiveShadow
          geometry={nodes.Base.geometry}
          material={materials.Concrete}
          position={[0.041, 29.974, 0]}
          scale={[1, 2, 1]}
        />
        <mesh
          name="Head"
          castShadow
          receiveShadow
          geometry={nodes.Head.geometry}
          material={materials["Material.002"]}
          position={[0.041, 36.7, 0]}
        />
        <mesh
          name="Roof"
          castShadow
          receiveShadow
          geometry={nodes.Roof.geometry}
          material={materials.RoofMaterial}
          position={[0.041, 40.105, 0]}
          rotation={[0, Math.PI / 4, 0]}
        />
        <pointLight
          name="Light001"
          intensity={271757.065}
          decay={2}
          position={[-4.441, 40.329, 15.95]}
          rotation={[-1.839, 0.602, 1.932]}
        />
        <group name="Cow" position={[-8, 35.972, 0]}>
          <mesh
            name="Cube_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials["Matériau.002"]}
          />
          <mesh
            name="Cube_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials["Matériau.001"]}
          />
          <mesh
            name="Cube_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube_3.geometry}
            material={materials.Matériau}
          />
          <mesh
            name="Cube_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube_4.geometry}
            material={materials["Matériau.003"]}
          />
          <mesh
            name="Cube_5"
            castShadow
            receiveShadow
            geometry={nodes.Cube_5.geometry}
            material={materials["Matériau.004"]}
          />
          <pointLight
            name="Point"
            intensity={27175.707}
            decay={2}
            color="#00ffff"
            position={[-1.466, 1.698, 2.119]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <mesh
          name="Text"
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={materials.Material}
          position={[-2, 33, 2.62]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.49, 1, 1.429]}
        >
          <mesh
            name="Text001"
            castShadow
            receiveShadow
            geometry={nodes.Text001.geometry}
            material={materials.Material}
            position={[2.684, -5.24, 0]}
            rotation={[0, 0, Math.PI]}
          />
          <mesh
            name="Text002"
            castShadow
            receiveShadow
            geometry={nodes.Text002.geometry}
            material={materials.Material}
            position={[3.1, -0.52, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[1.128, 0.671, 1]}
          />
          <mesh
            name="Text003"
            castShadow
            receiveShadow
            geometry={nodes.Text003.geometry}
            material={materials.Material}
            position={[-0.416, -4.72, 0]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[1.128, 0.671, 1]}
          />
        </mesh>
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Concrete}
          position={[0.041, 23.049, 3.47]}
          scale={[2, 2.5, 1]}
        />
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.RoofMaterial}
          position={[0.041, 26.536, 3.47]}
          scale={[2.25, 1, 1.25]}
        />
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
          position={[-7.455, 23.622, 0.01]}
          scale={[5, 3, 2.25]}
        />
        <mesh
          name="Cube003"
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials.RoofMaterial}
          position={[-7.455, 27.621, 0.01]}
          scale={[5, 1, 2.25]}
        />
        <mesh
          name="Cube004"
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={nodes.Cube004.material}
          position={[-0.017, 23.622, -7.489]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[5, 3, 2.25]}
        />
        <mesh
          name="Cube005"
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials.RoofMaterial}
          position={[-0.017, 27.621, -7.489]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[5, 1, 2.25]}
        />
        <mesh
          name="Cube006"
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials["Material.005"]}
          position={[0.041, 26.536, 3.47]}
          scale={[2.25, 1, 1.25]}
        />
        <mesh
          name="Cube007"
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials["Material.006"]}
          position={[0.041, 23.049, 3.47]}
          scale={[2, 2.5, 1]}
        />
        <mesh
          name="Cube008"
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials["Material.005"]}
          position={[3.703, 25.555, -5]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[2.3, 0.5, 1.5]}
        />
        <mesh
          name="Cube009"
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials["Material.006"]}
          position={[3.708, 22.799, -5]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[2, 2.25, 1.5]}
        />
        <mesh
          name="NeonSignBase"
          castShadow
          receiveShadow
          geometry={nodes.NeonSignBase.geometry}
          material={materials["Material.002"]}
          position={[0.041, 19.515, 0]}
        >
          <group
            name="Empty"
            position={[7.079, 0.485, 7.12]}
            rotation={[0, Math.PI / 4, 0]}
          />
          <mesh
            name="Text004"
            castShadow
            receiveShadow
            geometry={nodes.Text004.geometry}
            material={materials.NeonText}
            position={[7.079, 0.485, 7.12]}
            rotation={[Math.PI / 2, 0, -Math.PI / 4]}
          />
        </mesh>
        <mesh
          name="BezierCurve"
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve.geometry}
          material={materials["Light String"]}
          position={[-13.499, 35.303, -3.545]}
        />
        <mesh
          name="BezierCurve001"
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve001.geometry}
          material={materials["Light String"]}
          position={[-0.897, 35.278, -13.564]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="BlinkerCube"
          castShadow
          receiveShadow
          geometry={nodes.BlinkerCube.geometry}
          material={materials["Material.001"]}
          position={[-3.213, 33.357, -2.15]}
        />
        <pointLight
          name="Blinker"
          intensity={54351.413}
          decay={2}
          color="#f700ff"
          position={[-3.213, 33.357, -2.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="BlinkerCube001"
          castShadow
          receiveShadow
          geometry={nodes.BlinkerCube001.geometry}
          material={materials["Material.001"]}
          position={[-5.268, 31.674, -2.109]}
        />
        <mesh
          name="BlinkerCube002"
          castShadow
          receiveShadow
          geometry={nodes.BlinkerCube002.geometry}
          material={materials["Material.001"]}
          position={[-7.323, 30.6, -2.057]}
        />
        <mesh
          name="BlinkerCube003"
          castShadow
          receiveShadow
          geometry={nodes.BlinkerCube003.geometry}
          material={materials["Material.001"]}
          position={[-9.079, 29.712, -2.181]}
        />
        <mesh
          name="BlinkerCube004"
          castShadow
          receiveShadow
          geometry={nodes.BlinkerCube004.geometry}
          material={materials["Material.001"]}
          position={[-10.793, 29.103, -2.181]}
        />
        <pointLight
          name="Blinker001"
          intensity={54351.413}
          decay={2}
          color="#0028ff"
          position={[-5.184, 31.734, -2.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Blinker002_1"
          intensity={54351.413}
          decay={2}
          color="#ff000e"
          position={[-7.347, 30.559, -2.086]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Blinker003_1"
          intensity={54351.413}
          decay={2}
          color="#12ff00"
          position={[-9.046, 29.545, -2.125]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Blinker004_1"
          intensity={54351.413}
          decay={2}
          color="#fffb00"
          position={[-10.798, 29.153, -2.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="BlinkerCube005"
          castShadow
          receiveShadow
          geometry={nodes.BlinkerCube005.geometry}
          material={materials["Material.001"]}
          position={[-2.185, 33.264, -3.506]}
        />
        <mesh
          name="BlinkerCube006"
          castShadow
          receiveShadow
          geometry={nodes.BlinkerCube006.geometry}
          material={materials["Material.001"]}
          position={[-2.278, 31.955, -4.815]}
        />
        <mesh
          name="BlinkerCube007"
          castShadow
          receiveShadow
          geometry={nodes.BlinkerCube007.geometry}
          material={materials["Material.001"]}
          position={[-2.302, 30.717, -6.754]}
        />
        <mesh
          name="BlinkerCube008"
          castShadow
          receiveShadow
          geometry={nodes.BlinkerCube008.geometry}
          material={materials["Material.001"]}
          position={[-2.302, 29.782, -8.764]}
        />
        <mesh
          name="BlinkerCube009"
          castShadow
          receiveShadow
          geometry={nodes.BlinkerCube009.geometry}
          material={materials["Material.001"]}
          position={[-2.302, 29.034, -10.821]}
        />
        <pointLight
          name="Blinker005_1"
          intensity={54351.413}
          decay={2}
          color="#00ffff"
          position={[-2.314, 33.357, -3.499]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Blinker006"
          intensity={54351.413}
          decay={2}
          color="#0eff00"
          position={[-2.241, 31.734, -4.888]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Blinker007_1"
          intensity={54351.413}
          decay={2}
          color="#ff8f00"
          position={[-2.362, 30.559, -6.704]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Blinker008_1"
          intensity={54351.413}
          decay={2}
          color="#ff2400"
          position={[-2.303, 29.545, -8.622]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Blinker009_1"
          intensity={54351.413}
          decay={2}
          color="#9f00ff"
          position={[-2.298, 29.153, -10.773]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}
export default Model3;
useGLTF.preload("./models/hackmerced3.gltf");